<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eefextwidgetsnebula" nsURI="http://www.eclipse.org/eef/ext/widgets/nebula"
    nsPrefix="eef-ext-widgets-nebula">
  <eClassifiers xsi:type="ecore:EClass" name="EEFExtNebulaRichTextDescription" eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFWidgetDescription">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Allows the edition of a Nebula RichText."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueExpression" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates how to display the input value."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editExpression" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the behavior executed when the end-user updates the value of the Nebula RichText field."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//EEFExtNebulaRichTextWidgetStyle"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The style of the Nebula RichText widget"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalStyles" upperBound="-1"
        eType="#//EEFExtNebulaRichTextConditionalStyle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEFExtNebulaRichTextWidgetStyle" eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFWidgetStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The style of the Nebula RichText widget"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEFExtNebulaRichTextConditionalStyle"
      eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFConditionalStyle">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The conditional style of the Nebula RichText widget"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//EEFExtNebulaRichTextWidgetStyle"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The style of the Nebula RichText widget"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
